# Generated by Django 5.2.8 on 2025-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_product_brand_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
